- name: Example playbook
  hosts: all
  remote_user: opc
  become: true
  become_user: mqm

  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/mqm/bin"
    BASH_ENV: "{{ ansible_env.HOME }}/.bash_profile"

  tasks:
    - name: Display PATH environment variable
      shell: echo $PATH
      register: output

    - name: Display output
      debug:
        var: output.stdout_lines
    - name: Execute dspmqver command
      command: dspmqver
      register: mqver_output
    - name: Display dspmqver output
      become: true
      debug:
        var: mqver_output.stdout_lines
    - name: stop the queue managers for instance-1
      shell: |
        endmqm -i QM1
        dltmqm QM1
      when: inventory_hostname == groups['mq-servers'][0]
    - name: stop the queue managers for instance-2
      shell: |
        endmqm -i QM2
        dltmqm QM2
      when: inventory_hostname == groups['mq-servers'][1]
    - name: stop the queue managers for instance-3
      shell: |
        endmqm -i QM3
        dltmqm QM3
      when: inventory_hostname == groups['mq-servers'][2]
